### ISSUE TITLE
dmenu mode: cant use another string than options

### ISSUE THREAD

**Issue by ghost** [davawen/keal#4]
I noticed that in dmenu mode, when I type something that is not a choice, keal doesnt print what I typed and keeps prompting me for choosing one of the options.
Since it is the behavior of others dmenus, it would be cool to have that in keal.

**Comment by davawen** [comment]
Didn't know that, thanks! It should be pretty simple to implement.

**Comment by davawen** [comment]
Closed by ebf71b32ba3571474bbf98907363c1513b05cd12.

**Comment by davawen** [comment]
Whoops! broke main branch. fixed with latest commit.
